export const styles ={
    backgroundImage: {
      flex: 1,
      resizeMode: 'cover', 
    },
    container: {
      flex: 1,
      paddingTop: 150, 
      alignItems: 'center',
      padding: 20,
      
      elevation: 5,
    },
    bottom: {
      flex: 1,
      paddingTop: 40, 
      alignItems: 'left',
      padding: 20,
      elevation: 5,
    },
    signup: {
      color: '#fff',
      fontSize: 17,
      fontWeight: 'bold',
      textAlign: 'left',
      marginBottom: 16,
      color: '#fff', 
      paddingTop: 20,
    },
    input: {
      width: '100%',
      height: 50,
      borderColor: '#105',
      borderWidth: 3,
      marginBottom: 35,
      paddingLeft: 80,
      borderRadius: 20,
      backgroundColor: 'rgba(255, 255, 255, 0.8)',
      fontWeight:'bold',
      fontSize: 20,
      color: '#105', 
    },
    buttonS: {
      backgroundColor: 'rgba(40,61,125,0.9)',
      padding: 10,
      borderRadius: 15,
      width: '80%',
    },
    buttonL: {
      backgroundColor: 'rgba(40,61,125,0.9)',
      padding: 10,
      borderRadius: 15,
      width: '80%',
    },
    buttonText: {
      color: 'white',
      textAlign: 'center',
      fontWeight: 'bold',
    },
  };